{
//=========Macro generated from canvas: c1/c1
//=========  (Wed Mar 30 03:17:33 2016) by ROOT version5.30/03
/*   TCanvas *c1 = new TCanvas("c1", "c1",12,61,700,500);
   c1->Range(-0.625,-2087.794,5.625,18790.14);
   c1->SetFillColor(0);
   c1->SetBorderMode(0);
   c1->SetBorderSize(2);
   c1->SetFrameBorderMode(0);
   c1->SetFrameBorderMode(0);
*/ 

   TH1D *hnomatch_e_ratio_arm1_py = new TH1D("hnomatch_e_ratio_arm1_py","Nomatch ratio Arm 1",100,0,5);
   hnomatch_e_ratio_arm1_py->SetBinContent(1,15907);
   hnomatch_e_ratio_arm1_py->SetBinContent(2,12687);
   hnomatch_e_ratio_arm1_py->SetBinContent(3,13624);
   hnomatch_e_ratio_arm1_py->SetBinContent(4,14357);
   hnomatch_e_ratio_arm1_py->SetBinContent(5,13763);
   hnomatch_e_ratio_arm1_py->SetBinContent(6,13981);
   hnomatch_e_ratio_arm1_py->SetBinContent(7,12599);
   hnomatch_e_ratio_arm1_py->SetBinContent(8,11734);
   hnomatch_e_ratio_arm1_py->SetBinContent(9,9990);
   hnomatch_e_ratio_arm1_py->SetBinContent(10,9085);
   hnomatch_e_ratio_arm1_py->SetBinContent(11,7687);
   hnomatch_e_ratio_arm1_py->SetBinContent(12,6604);
   hnomatch_e_ratio_arm1_py->SetBinContent(13,5216);
   hnomatch_e_ratio_arm1_py->SetBinContent(14,4738);
   hnomatch_e_ratio_arm1_py->SetBinContent(15,4141);
   hnomatch_e_ratio_arm1_py->SetBinContent(16,3129);
   hnomatch_e_ratio_arm1_py->SetBinContent(17,2410);
   hnomatch_e_ratio_arm1_py->SetBinContent(18,1893);
   hnomatch_e_ratio_arm1_py->SetBinContent(19,1631);
   hnomatch_e_ratio_arm1_py->SetBinContent(20,1187);
   hnomatch_e_ratio_arm1_py->SetBinContent(21,923);
   hnomatch_e_ratio_arm1_py->SetBinContent(22,764);
   hnomatch_e_ratio_arm1_py->SetBinContent(23,701);
   hnomatch_e_ratio_arm1_py->SetBinContent(24,512);
   hnomatch_e_ratio_arm1_py->SetBinContent(25,464);
   hnomatch_e_ratio_arm1_py->SetBinContent(26,408);
   hnomatch_e_ratio_arm1_py->SetBinContent(27,335);
   hnomatch_e_ratio_arm1_py->SetBinContent(28,210);
   hnomatch_e_ratio_arm1_py->SetBinContent(29,172);
   hnomatch_e_ratio_arm1_py->SetBinContent(30,130);
   hnomatch_e_ratio_arm1_py->SetBinContent(31,130);
   hnomatch_e_ratio_arm1_py->SetBinContent(32,128);
   hnomatch_e_ratio_arm1_py->SetBinContent(33,109);
   hnomatch_e_ratio_arm1_py->SetBinContent(34,108);
   hnomatch_e_ratio_arm1_py->SetBinContent(35,65);
   hnomatch_e_ratio_arm1_py->SetBinContent(36,48);
   hnomatch_e_ratio_arm1_py->SetBinContent(37,66);
   hnomatch_e_ratio_arm1_py->SetBinContent(38,85);
   hnomatch_e_ratio_arm1_py->SetBinContent(39,59);
   hnomatch_e_ratio_arm1_py->SetBinContent(40,21);
   hnomatch_e_ratio_arm1_py->SetBinContent(41,49);
   hnomatch_e_ratio_arm1_py->SetBinContent(42,30);
   hnomatch_e_ratio_arm1_py->SetBinContent(43,28);
   hnomatch_e_ratio_arm1_py->SetBinContent(44,27);
   hnomatch_e_ratio_arm1_py->SetBinContent(45,34);
   hnomatch_e_ratio_arm1_py->SetBinContent(46,13);
   hnomatch_e_ratio_arm1_py->SetBinContent(47,25);
   hnomatch_e_ratio_arm1_py->SetBinContent(48,22);
   hnomatch_e_ratio_arm1_py->SetBinContent(50,31);
   hnomatch_e_ratio_arm1_py->SetBinContent(51,7);
   hnomatch_e_ratio_arm1_py->SetBinContent(52,7);
   hnomatch_e_ratio_arm1_py->SetBinContent(53,33);
   hnomatch_e_ratio_arm1_py->SetBinContent(54,4);
   hnomatch_e_ratio_arm1_py->SetBinContent(55,7);
   hnomatch_e_ratio_arm1_py->SetBinContent(58,14);
   hnomatch_e_ratio_arm1_py->SetBinContent(59,14);
   hnomatch_e_ratio_arm1_py->SetBinContent(60,29);
   hnomatch_e_ratio_arm1_py->SetBinContent(62,7);
   hnomatch_e_ratio_arm1_py->SetBinContent(63,1);
   hnomatch_e_ratio_arm1_py->SetBinContent(64,2);
   hnomatch_e_ratio_arm1_py->SetBinContent(66,8);
   hnomatch_e_ratio_arm1_py->SetBinContent(67,1);
   hnomatch_e_ratio_arm1_py->SetBinContent(68,2);
   hnomatch_e_ratio_arm1_py->SetBinContent(69,1);
   hnomatch_e_ratio_arm1_py->SetBinContent(72,2);
   hnomatch_e_ratio_arm1_py->SetBinContent(73,7);
   hnomatch_e_ratio_arm1_py->SetBinContent(74,1);
   hnomatch_e_ratio_arm1_py->SetBinContent(76,9);
   hnomatch_e_ratio_arm1_py->SetBinContent(80,11);
   hnomatch_e_ratio_arm1_py->SetBinContent(82,15);
   hnomatch_e_ratio_arm1_py->SetBinContent(85,4);
   hnomatch_e_ratio_arm1_py->SetBinContent(87,6);
   hnomatch_e_ratio_arm1_py->SetBinContent(88,4);
   hnomatch_e_ratio_arm1_py->SetBinContent(98,1);
   hnomatch_e_ratio_arm1_py->SetBinContent(99,2);
   hnomatch_e_ratio_arm1_py->SetBinContent(100,5);
   hnomatch_e_ratio_arm1_py->SetBinContent(101,45);
   hnomatch_e_ratio_arm1_py->SetEntries(172309);
   
   TPaveStats *ptstats = new TPaveStats(0.78,0.775,0.98,0.935,"brNDC");
   ptstats->SetName("stats");
   ptstats->SetBorderSize(1);
   ptstats->SetFillColor(0);
   ptstats->SetTextAlign(12);
   ptstats->SetTextFont(42);
   TText *text = ptstats->AddText("hnomatch_e_ratio_arm1_py");
   text->SetTextSize(0.0368);
   text = ptstats->AddText("Entries = 172309 ");
   text = ptstats->AddText("Mean  = 0.3694");
   text = ptstats->AddText("RMS   = 0.3077");
   ptstats->SetOptStat(1111);
   ptstats->SetOptFit(0);
   ptstats->Draw();
   hnomatch_e_ratio_arm1_py->GetListOfFunctions()->Add(ptstats);
   ptstats->SetParent(hnomatch_e_ratio_arm1_py->GetListOfFunctions());

   Int_t ci;   // for color index setting
   ci = TColor::GetColor("#000099");
   hnomatch_e_ratio_arm1_py->SetLineColor(ci);
   hnomatch_e_ratio_arm1_py->GetXaxis()->SetTitle("Match ratio");
   hnomatch_e_ratio_arm1_py->GetXaxis()->SetLabelFont(42);
   hnomatch_e_ratio_arm1_py->GetXaxis()->SetLabelSize(0.035);
   hnomatch_e_ratio_arm1_py->GetXaxis()->SetTitleSize(0.035);
   hnomatch_e_ratio_arm1_py->GetXaxis()->SetTitleFont(42);
   hnomatch_e_ratio_arm1_py->GetYaxis()->SetLabelFont(42);
   hnomatch_e_ratio_arm1_py->GetYaxis()->SetLabelSize(0.035);
   hnomatch_e_ratio_arm1_py->GetYaxis()->SetTitleSize(0.035);
   hnomatch_e_ratio_arm1_py->GetYaxis()->SetTitleFont(42);
   hnomatch_e_ratio_arm1_py->GetZaxis()->SetLabelFont(42);
   hnomatch_e_ratio_arm1_py->GetZaxis()->SetLabelSize(0.035);
   hnomatch_e_ratio_arm1_py->GetZaxis()->SetTitleSize(0.035);
   hnomatch_e_ratio_arm1_py->GetZaxis()->SetTitleFont(42);
   hnomatch_e_ratio_arm1_py->SetLineColor(kRed);
   hnomatch_e_ratio_arm1_py->DrawNormalized("same");
   
   TPaveText *pt = new TPaveText(0.3233333,0.94,0.6766667,0.995,"blNDC");
   pt->SetName("title");
   pt->SetBorderSize(0);
   pt->SetFillColor(0);
   pt->SetTextFont(42);
   text = pt->AddText("Nomatch ratio Arm 1");
   pt->Draw();
   c1->Modified();
   c1->cd();
   c1->SetSelected(c1);
}
