{
//=========Macro generated from canvas: c1/c1
//=========  (Wed Mar 30 03:18:22 2016) by ROOT version5.30/03
   TCanvas *c1 = new TCanvas("c1", "c1",12,61,700,500);
   c1->Range(-0.625,-12707.89,5.625,114371);
   c1->SetFillColor(0);
   c1->SetBorderMode(0);
   c1->SetBorderSize(2);
   c1->SetFrameBorderMode(0);
   c1->SetFrameBorderMode(0);
   
   TH1D *hnomatch_e_ratio_arm1_px = new TH1D("hnomatch_e_ratio_arm1_px","Nomatch ratio Arm 1",100,0,5);
   hnomatch_e_ratio_arm1_px->SetBinContent(1,96822);
   hnomatch_e_ratio_arm1_px->SetBinContent(2,30474);
   hnomatch_e_ratio_arm1_px->SetBinContent(3,14789);
   hnomatch_e_ratio_arm1_px->SetBinContent(4,8520);
   hnomatch_e_ratio_arm1_px->SetBinContent(5,5160);
   hnomatch_e_ratio_arm1_px->SetBinContent(6,3567);
   hnomatch_e_ratio_arm1_px->SetBinContent(7,2473);
   hnomatch_e_ratio_arm1_px->SetBinContent(8,1813);
   hnomatch_e_ratio_arm1_px->SetBinContent(9,1488);
   hnomatch_e_ratio_arm1_px->SetBinContent(10,1083);
   hnomatch_e_ratio_arm1_px->SetBinContent(11,801);
   hnomatch_e_ratio_arm1_px->SetBinContent(12,710);
   hnomatch_e_ratio_arm1_px->SetBinContent(13,553);
   hnomatch_e_ratio_arm1_px->SetBinContent(14,463);
   hnomatch_e_ratio_arm1_px->SetBinContent(15,380);
   hnomatch_e_ratio_arm1_px->SetBinContent(16,329);
   hnomatch_e_ratio_arm1_px->SetBinContent(17,267);
   hnomatch_e_ratio_arm1_px->SetBinContent(18,221);
   hnomatch_e_ratio_arm1_px->SetBinContent(19,213);
   hnomatch_e_ratio_arm1_px->SetBinContent(20,162);
   hnomatch_e_ratio_arm1_px->SetBinContent(21,144);
   hnomatch_e_ratio_arm1_px->SetBinContent(22,125);
   hnomatch_e_ratio_arm1_px->SetBinContent(23,122);
   hnomatch_e_ratio_arm1_px->SetBinContent(24,125);
   hnomatch_e_ratio_arm1_px->SetBinContent(25,104);
   hnomatch_e_ratio_arm1_px->SetBinContent(26,75);
   hnomatch_e_ratio_arm1_px->SetBinContent(27,76);
   hnomatch_e_ratio_arm1_px->SetBinContent(28,60);
   hnomatch_e_ratio_arm1_px->SetBinContent(29,64);
   hnomatch_e_ratio_arm1_px->SetBinContent(30,65);
   hnomatch_e_ratio_arm1_px->SetBinContent(31,51);
   hnomatch_e_ratio_arm1_px->SetBinContent(32,54);
   hnomatch_e_ratio_arm1_px->SetBinContent(33,31);
   hnomatch_e_ratio_arm1_px->SetBinContent(34,44);
   hnomatch_e_ratio_arm1_px->SetBinContent(35,35);
   hnomatch_e_ratio_arm1_px->SetBinContent(36,35);
   hnomatch_e_ratio_arm1_px->SetBinContent(37,34);
   hnomatch_e_ratio_arm1_px->SetBinContent(38,30);
   hnomatch_e_ratio_arm1_px->SetBinContent(39,20);
   hnomatch_e_ratio_arm1_px->SetBinContent(40,31);
   hnomatch_e_ratio_arm1_px->SetBinContent(41,19);
   hnomatch_e_ratio_arm1_px->SetBinContent(42,15);
   hnomatch_e_ratio_arm1_px->SetBinContent(43,16);
   hnomatch_e_ratio_arm1_px->SetBinContent(44,16);
   hnomatch_e_ratio_arm1_px->SetBinContent(45,16);
   hnomatch_e_ratio_arm1_px->SetBinContent(46,13);
   hnomatch_e_ratio_arm1_px->SetBinContent(47,19);
   hnomatch_e_ratio_arm1_px->SetBinContent(48,13);
   hnomatch_e_ratio_arm1_px->SetBinContent(49,15);
   hnomatch_e_ratio_arm1_px->SetBinContent(50,11);
   hnomatch_e_ratio_arm1_px->SetBinContent(51,17);
   hnomatch_e_ratio_arm1_px->SetBinContent(52,13);
   hnomatch_e_ratio_arm1_px->SetBinContent(53,14);
   hnomatch_e_ratio_arm1_px->SetBinContent(54,9);
   hnomatch_e_ratio_arm1_px->SetBinContent(55,14);
   hnomatch_e_ratio_arm1_px->SetBinContent(56,11);
   hnomatch_e_ratio_arm1_px->SetBinContent(57,9);
   hnomatch_e_ratio_arm1_px->SetBinContent(58,12);
   hnomatch_e_ratio_arm1_px->SetBinContent(59,12);
   hnomatch_e_ratio_arm1_px->SetBinContent(60,11);
   hnomatch_e_ratio_arm1_px->SetBinContent(61,6);
   hnomatch_e_ratio_arm1_px->SetBinContent(62,4);
   hnomatch_e_ratio_arm1_px->SetBinContent(63,7);
   hnomatch_e_ratio_arm1_px->SetBinContent(64,9);
   hnomatch_e_ratio_arm1_px->SetBinContent(65,11);
   hnomatch_e_ratio_arm1_px->SetBinContent(66,4);
   hnomatch_e_ratio_arm1_px->SetBinContent(67,9);
   hnomatch_e_ratio_arm1_px->SetBinContent(68,5);
   hnomatch_e_ratio_arm1_px->SetBinContent(69,4);
   hnomatch_e_ratio_arm1_px->SetBinContent(70,9);
   hnomatch_e_ratio_arm1_px->SetBinContent(71,10);
   hnomatch_e_ratio_arm1_px->SetBinContent(72,5);
   hnomatch_e_ratio_arm1_px->SetBinContent(73,2);
   hnomatch_e_ratio_arm1_px->SetBinContent(74,2);
   hnomatch_e_ratio_arm1_px->SetBinContent(75,4);
   hnomatch_e_ratio_arm1_px->SetBinContent(76,4);
   hnomatch_e_ratio_arm1_px->SetBinContent(77,4);
   hnomatch_e_ratio_arm1_px->SetBinContent(78,6);
   hnomatch_e_ratio_arm1_px->SetBinContent(79,4);
   hnomatch_e_ratio_arm1_px->SetBinContent(80,5);
   hnomatch_e_ratio_arm1_px->SetBinContent(81,5);
   hnomatch_e_ratio_arm1_px->SetBinContent(82,2);
   hnomatch_e_ratio_arm1_px->SetBinContent(83,3);
   hnomatch_e_ratio_arm1_px->SetBinContent(84,6);
   hnomatch_e_ratio_arm1_px->SetBinContent(85,3);
   hnomatch_e_ratio_arm1_px->SetBinContent(86,3);
   hnomatch_e_ratio_arm1_px->SetBinContent(87,3);
   hnomatch_e_ratio_arm1_px->SetBinContent(88,4);
   hnomatch_e_ratio_arm1_px->SetBinContent(89,3);
   hnomatch_e_ratio_arm1_px->SetBinContent(90,3);
   hnomatch_e_ratio_arm1_px->SetBinContent(91,1);
   hnomatch_e_ratio_arm1_px->SetBinContent(92,5);
   hnomatch_e_ratio_arm1_px->SetBinContent(93,2);
   hnomatch_e_ratio_arm1_px->SetBinContent(94,1);
   hnomatch_e_ratio_arm1_px->SetBinContent(95,2);
   hnomatch_e_ratio_arm1_px->SetBinContent(96,2);
   hnomatch_e_ratio_arm1_px->SetBinContent(97,1);
   hnomatch_e_ratio_arm1_px->SetBinContent(98,2);
   hnomatch_e_ratio_arm1_px->SetBinContent(100,4);
   hnomatch_e_ratio_arm1_px->SetBinContent(101,252);
   hnomatch_e_ratio_arm1_px->SetEntries(172309);
   
   TPaveStats *ptstats = new TPaveStats(0.78,0.775,0.98,0.935,"brNDC");
   ptstats->SetName("stats");
   ptstats->SetBorderSize(1);
   ptstats->SetFillColor(0);
   ptstats->SetTextAlign(12);
   ptstats->SetTextFont(42);
   TText *text = ptstats->AddText("hnomatch_e_ratio_arm1_px");
   text->SetTextSize(0.0368);
   text = ptstats->AddText("Entries = 172309 ");
   text = ptstats->AddText("Mean  = 0.1087");
   text = ptstats->AddText("RMS   = 0.2268");
   ptstats->SetOptStat(1111);
   ptstats->SetOptFit(0);
   ptstats->Draw();
   hnomatch_e_ratio_arm1_px->GetListOfFunctions()->Add(ptstats);
   ptstats->SetParent(hnomatch_e_ratio_arm1_px->GetListOfFunctions());

   Int_t ci;   // for color index setting
   ci = TColor::GetColor("#000099");
   hnomatch_e_ratio_arm1_px->SetLineColor(ci);
   hnomatch_e_ratio_arm1_px->GetXaxis()->SetTitle("NoMatch ratio");
   hnomatch_e_ratio_arm1_px->GetXaxis()->SetLabelFont(42);
   hnomatch_e_ratio_arm1_px->GetXaxis()->SetLabelSize(0.035);
   hnomatch_e_ratio_arm1_px->GetXaxis()->SetTitleSize(0.035);
   hnomatch_e_ratio_arm1_px->GetXaxis()->SetTitleFont(42);
   hnomatch_e_ratio_arm1_px->GetYaxis()->SetLabelFont(42);
   hnomatch_e_ratio_arm1_px->GetYaxis()->SetLabelSize(0.035);
   hnomatch_e_ratio_arm1_px->GetYaxis()->SetTitleSize(0.035);
   hnomatch_e_ratio_arm1_px->GetYaxis()->SetTitleFont(42);
   hnomatch_e_ratio_arm1_px->GetZaxis()->SetLabelFont(42);
   hnomatch_e_ratio_arm1_px->GetZaxis()->SetLabelSize(0.035);
   hnomatch_e_ratio_arm1_px->GetZaxis()->SetTitleSize(0.035);
   hnomatch_e_ratio_arm1_px->GetZaxis()->SetTitleFont(42);
   hnomatch_e_ratio_arm1_px->DrawNormalized("");
   
   TPaveText *pt = new TPaveText(0.3233333,0.94,0.6766667,0.995,"blNDC");
   pt->SetName("title");
   pt->SetBorderSize(0);
   pt->SetFillColor(0);
   pt->SetTextFont(42);
   text = pt->AddText("Nomatch ratio Arm 1");
   pt->Draw();
   c1->Modified();
   c1->cd();
   c1->SetSelected(c1);
}
